version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5000:5000"
    depends_on:
      - "rest"
    volumes:
      - ./:/app
  rest:
    build:
      context: .
      dockerfile: Dockerfile.rest
    ports:
      - "8000:5000"
    depends_on:
      - "mongo"
    volumes:
      - ./:/app
    environment:
      - "MONGO_HOST=mongo"
  mongo:
    image: "mongo:4"
    ports:
      - "27017:27017"