FROM ubuntu:focal

RUN apt update -y
RUN apt install -y python3-pip

RUN mkdir -p /app
WORKDIR /app

COPY requirements-web.txt /app/requirements.txt
RUN pip3 install -r requirements.txt
COPY web.py /app/web.py
COPY templates /app/templates
COPY static /app/static 
# copies link instead of file, causing error 404
# solution below --> not sure if should be implemented, error 404 with .map files only

# RUN mkdir -p /app/static/{js,css,img}
# COPY node_modules/bootstrap/dist/css/bootstrap.min.css /app/static/css/bootstrap.min.css
# COPY node_modules/bootstrap/dist/js/bootstrap.bundle.min.js /app/static/js/bootstrap.bundle.min.js
# COPY node_modules/jquery/dist/jquery.min.js /app/static/js/jquery.min.js

CMD ["python3", "web.py"]

EXPOSE 5000
