FROM ubuntu:focal

RUN apt update -y
RUN apt install -y python3-pip

RUN mkdir -p /app
WORKDIR /app

COPY requirements-rest.txt /app/requirements.txt
RUN pip3 install -r requirements.txt
COPY rest.py /app/rest.py

CMD ["python3", "rest.py"]

EXPOSE 5000
